### ISSUE TITLE
Playwright e2e tests are visually broken

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#129]
Super awesome feature Kent, thanks! I'm already using it on my platform 🎉

However, even thought the e2e tests pass, they are visually broken as the Tailwind class CSS is not being injected onto the page:
<img width="994" alt="Screenshot 2023-06-03 at 12 11 06" src="https://github.com/epicweb-dev/epic-stack/assets/22457463/4eeb3541-9ab6-46d2-8901-3be8334d4e33">

### Update:
I've tracked the issue to the `window.location.reload()` line on the injected script.

_Originally posted by @andrecasal in https://github.com/epicweb-dev/epic-stack/issues/64#issuecomment-1574868851_

**Comment by kentcdodds** [comment]
I believe this is a bug in the playwright preview. If you run `npx playwright test --headed` you can watch the tests run and they all have the styles properly applied. You may also notice in your screenshot that the film strip at the top has the correct previews as well.

I would like to figure out how to solve this though because we'll likely have people with this question in the future. @pavelfeldman, do you know what could be causing this?

For some quick context, we released this feature based on the Client Hints spec (check the video): https://github.com/epicweb-dev/epic-stack/discussions/125

This involved a bit of client side JS that triggers a reload on the first visit for a new visitor: https://github.com/epicweb-dev/epic-stack/blob/e6f0e5a049789314ebfc96115ac2b0aaf3fe1f8f/app/utils/client-hints.tsx#L119

For some reason that `window.location.reload()` makes the CSS not show up in the preview during UI mode.

**Comment by kentcdodds** [comment]
@andrecasal, it would probably help the playwright team if we open an issue on their repo with a small, isolated reproduction (so, without the epic stack or even remix). Do you think you could put something together for that?

**Comment by andrecasal** [comment]
@kentcdodds Yeah I can give it a try 👍

**Comment by kentcdodds** [comment]
Thank you @andrecasal!

**Comment by andrecasal** [comment]
Created [this small repro](https://github.com/andrecasal/playwright-reload-bug), but I'm getting an error from Playwright:

```sh
Error: EISDIR: illegal operation on a directory, read
```

Playwright's config is trying to read a folder as if it was a file, but I can't find anything wrong with the `playwright.config.ts`

Any idea what's going on?

**Comment by kentcdodds** [comment]
That repo looks good to me. I would suggest you switch from Math.random() to sticking something in local storage and only refreshing if that's not in local storage yet. That would resemble our situation more.

As for the error, could you provide more of the error output? That seems pretty strange. If you can't figure it out, then that would definitely be another thing to open an issue about 😅

**Comment by andrecasal** [comment]
> That repo looks good to me. I would suggest you switch from Math.random() to sticking something in local storage and only refreshing if that's not in local storage yet. That would resemble our situation more.

Will do.

> As for the error, could you provide more of the error output? That seems pretty strange. If you can't figure it out, then that would definitely be another thing to open an issue about 😅

Here's the full output:
```sh
 *  Executing task: npm run test 


> playwright-reload-bug@1.0.0 test
> playwright test --ui

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:739:3)
    at tryReadSync (node:fs:439:20)
    at Object.readFileSync (node:fs:485:19)
    at loadTsconfig (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js:102:27)
    at loadSyncDefault (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js:64:18)
    at tsConfigLoader (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js:46:22)
    at loadAndValidateTsconfigForFile (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/common/transform.js:62:55)
    at resolveHook (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/common/transform.js:76:20)
    at Function.resolveFilename (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/common/transform.js:174:24)
    at Function.Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/andrecasal/Developer/Apps/playwright-reload-bug/playwright.config.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.f._compile (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.i.<computed>.ot._extensions.<computed> (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/common/transform.js:158:20)
    at requireOrImportDefaultObject (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/common/configLoader.js:80:53)
    at ConfigLoader.loadConfigFile (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/common/configLoader.js:53:26)
    at runTests (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/cli.js:120:55)
    at ji.<anonymous> (/Users/andrecasal/Developer/Apps/playwright-reload-bug/node_modules/@playwright/test/lib/cli.js:40:7) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}

 *  The terminal process "/usr/local/bin/zsh '-c', 'npm run test'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

If you have no idea either, I'll open an issue on Playwright's repo 😅

**Comment by andrecasal** [comment]
Thanks! I found it easier to add the tsconfig file.

I've [left an issue](https://github.com/microsoft/playwright/issues/23613) on Playwright's repo.

**Comment by andrecasal** [comment]
This is not related to the Epic Stack, so I'm closing this one.

**Comment by andrecasal** [comment]
Whoops, it turns out it's our fault... sort of.

> @andrecasal the `toHaveTitle` condition in your test is not good: it's racing against the in-page reload. You'll have to come up with a condition that actually waits for the page stable state.
> 
> Hope this helps!

_Originally posted by @aslushnikov in https://github.com/microsoft/playwright/issues/23613#issuecomment-1589683425_

**Comment by kentcdodds** [comment]
Nah, I'm pretty sure this is a playwright issue. I replied.

**Comment by kentcdodds** [comment]
Yep, this is a playwright thing: https://github.com/microsoft/playwright/issues/23709
