### ISSUE TITLE
No route matches url "/mockServiceWorker.js"

### ISSUE THREAD

**Issue by dchadcluff** [epicweb-dev/epic-stack#198]
I get this error for every route. Setup a fresh instance of Epic Stack to confirm and this is the first thing that comes up.

```
GET / 200 - - 28.852 ms
ErrorResponse {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/mockServiceWorker.js"',
  error: Error: No route matches URL "/mockServiceWorker.js"
      at getInternalRouterError (/temp/epicstack/epicstack/node_modules/@remix-run/router/dist/router.cjs.js:11:81684)
      at Object.query (/temp/epicstack/epicstack/node_modules/@remix-run/router/dist/router.cjs.js:11:59891)
      at handleDocumentRequestRR (/temp/epicstack/epicstack/node_modules/@remix-run/server-runtime/dist/server.js:11:4509)
      at requestHandler (/temp/epicstack/epicstack/node_modules/@remix-run/server-runtime/dist/server.js:11:1850)
      at /temp/epicstack/epicstack/node_modules/@remix-run/express/dist/server.js:11:426
}
No routes matched location "/mockServiceWorker.js" 
GET /mockServiceWorker.js 404 - - 56.179 ms
```
The route does load, but every request is accompanied by this error log.

**Comment by kentcdodds** [comment]
You've got a service worker installed on that location, probably from another at you work on, and it's trying to load that file. Go to your browser DevTools settings and delete the service worker.

Cheers!
