### ISSUE TITLE
I get "refspec main does not match any" on setup

### ISSUE THREAD

**Issue by iamrane** [epicweb-dev/epic-stack#199]
Hi!
I was just trying out this awesome stack. Its basically a perfect match for me :)
 
But when Im following all the scripts i get "refspec main does not match any. " when the script is trying to setup git actions. After i set the FLY_API_TOKEN.

```
error: src refspec main does not match any.
error: failed to push some refs to 'git@github.com:iamrane/epic.git'
Error: Command failed with exit code 1: git push -u origin main
    at makeError (file:///Users/my-user/epic/remix.init/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///Users/my-user/epic/remix.init/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async setupDeployment (file:///Users/my-user/epic/remix.init/index.mjs:260:4)
    at async main (file:///Users/my-user/epic/remix.init/index.mjs:87:2)
    at async module.exports (/Users/my-user/epic/remix.init/index.js:3:2)
    at async Object.init (/Users/my-user/.npm/_npx/5164864a48bff686/node_modules/@remix-run/dev/dist/cli/commands.js:144:5)
    at async Object.run (/Users/my-user/.npm/_npx/5164864a48bff686/node_modules/@remix-run/dev/dist/cli/run.js:449:13) {
  shortMessage: 'Command failed with exit code 1: git push -u origin main',
```
`git push -u origin main` is not working when im doing it in the terminal, I need to run `git branch -M main` first. Then it works. Is there some kind of config when Im creating the repository I need to have in order?

I'm using node 18.

**Comment by kentcdodds** [comment]
This is probably the same problem as #149

**Comment by iamrane** [comment]
Weird thing because I'm using the classic token setup.

**Comment by iamrane** [comment]
I solved the issue.
The problem was that your primary branch is main and mine was master. And I couldn't change my primary branch because of old git version. Now I updated git, changed my primary branch to main it worked like a charm :)
