### ISSUE TITLE
Initial deploy assumes git url, though user may be using https path

### ISSUE THREAD

**Issue by sys13** [epicweb-dev/epic-stack#260]
```
? Would you like to commit and push your changes? Yes
📦 Committing and pushing...
[main (root-commit) 957621f] Initial commit
 238 files changed, 45380 insertions(+)
 create mode 100644 .env.example
 create mode 100644 .eslintrc.cjs
 create mode 100644 .github/PULL_REQUEST_TEMPLATE.md
 create mode 100644 .github/workflows/deploy.yml
 create mode 100644 .gitignore
 create mode 100644 .npmrc
 create mode 100644 .prettierignore
 create mode 100644 .prettierrc.cjs
 create mode 100644 .vscode/extensions.json
 create mode 100644 .vscode/settings.json
 create mode 100644 README.md
 create mode 100644 app/components/confetti.tsx
 create mode 100644 app/components/error-boundary.tsx
 create mode 100644 app/components/forms.tsx
 create mode 100644 app/components/spacer.tsx
 create mode 100644 app/components/spinner.tsx
 create mode 100644 app/components/ui/README.md
 create mode 100644 app/components/ui/button.tsx
 create mode 100644 app/components/ui/checkbox.tsx
 create mode 100644 app/components/ui/dialog.tsx
 create mode 100644 app/components/ui/dropdown-menu.tsx
 create mode 100644 app/components/ui/icon.svg
 create mode 100644 app/components/ui/icon.tsx
 create mode 100644 app/components/ui/input.tsx
 create mode 100644 app/components/ui/label.tsx
 create mode 100644 app/components/ui/status-button.tsx
 create mode 100644 app/components/ui/textarea.tsx
 create mode 100644 app/components/ui/toast.tsx
 create mode 100644 app/components/ui/toaster.tsx
 create mode 100644 app/components/ui/tooltip.tsx
 create mode 100644 app/components/ui/use-toast.ts
 create mode 100644 app/entry.client.tsx
 create mode 100644 app/entry.server.tsx
 create mode 100644 app/root.tsx
 create mode 100644 app/routes/_auth+/forgot-password/email.server.tsx
 create mode 100644 app/routes/_auth+/forgot-password/index.tsx
 create mode 100644 app/routes/_auth+/forgot-password_.verify.tsx
 create mode 100644 app/routes/_auth+/login.tsx
 create mode 100644 app/routes/_auth+/logout.tsx
 create mode 100644 app/routes/_auth+/onboarding.tsx
 create mode 100644 app/routes/_auth+/reset-password.tsx
 create mode 100644 app/routes/_auth+/signup/email.server.tsx
 create mode 100644 app/routes/_auth+/signup/index.tsx
 create mode 100644 app/routes/_auth+/signup_.verify.tsx
 create mode 100644 app/routes/_marketing+/about.tsx
 create mode 100644 app/routes/_marketing+/index.tsx
 create mode 100644 app/routes/_marketing+/logos/docker.png
 create mode 100644 app/routes/_marketing+/logos/eslint.svg
 create mode 100644 app/routes/_marketing+/logos/faker.svg
 create mode 100644 app/routes/_marketing+/logos/fly.svg
 create mode 100644 app/routes/_marketing+/logos/github.svg
 create mode 100644 app/routes/_marketing+/logos/logos.ts
 create mode 100644 app/routes/_marketing+/logos/msw.svg
 create mode 100644 app/routes/_marketing+/logos/playwright.svg
 create mode 100644 app/routes/_marketing+/logos/prettier.svg
 create mode 100644 app/routes/_marketing+/logos/prisma.svg
 create mode 100644 app/routes/_marketing+/logos/radix.svg
 create mode 100644 app/routes/_marketing+/logos/react-email.svg
 create mode 100644 app/routes/_marketing+/logos/remix.png
 create mode 100644 app/routes/_marketing+/logos/resend.svg
 create mode 100644 app/routes/_marketing+/logos/sentry.svg
 create mode 100644 app/routes/_marketing+/logos/shadcn-ui.svg
 create mode 100644 app/routes/_marketing+/logos/sqlite.svg
 create mode 100644 app/routes/_marketing+/logos/stars.jpg
 create mode 100644 app/routes/_marketing+/logos/tailwind.svg
 create mode 100644 app/routes/_marketing+/logos/testing-library.png
 create mode 100644 app/routes/_marketing+/logos/typescript.svg
 create mode 100644 app/routes/_marketing+/logos/vitest.svg
 create mode 100644 app/routes/_marketing+/logos/zod.svg
 create mode 100644 app/routes/_marketing+/privacy.tsx
 create mode 100644 app/routes/_marketing+/support.tsx
 create mode 100644 app/routes/_marketing+/tos.tsx
 create mode 100644 app/routes/admin+/cache.tsx
 create mode 100644 app/routes/admin+/cache_.lru.$cacheKey.ts
 create mode 100644 app/routes/admin+/cache_.sqlite.$cacheKey.ts
 create mode 100644 app/routes/admin+/cache_.sqlite.tsx
 create mode 100644 app/routes/me.tsx
 create mode 100644 app/routes/resources+/delete-image.test.tsx
 create mode 100644 app/routes/resources+/delete-image.tsx
 create mode 100644 app/routes/resources+/delete-note.tsx
 create mode 100644 app/routes/resources+/file.$fileId.tsx
 create mode 100644 app/routes/resources+/healthcheck.tsx
 create mode 100644 app/routes/resources+/image-upload.tsx
 create mode 100644 app/routes/resources+/login.tsx
 create mode 100644 app/routes/resources+/note-editor.tsx
 create mode 100644 app/routes/resources+/theme/index.tsx
 create mode 100644 app/routes/resources+/theme/theme-session.server.ts
 create mode 100644 app/routes/resources+/verify.tsx
 create mode 100644 app/routes/settings+/profile.photo.tsx
 create mode 100644 app/routes/settings+/profile.tsx
 create mode 100644 app/routes/settings+/profile.two-factor.index.tsx
 create mode 100644 app/routes/settings+/profile.two-factor.tsx
 create mode 100644 app/routes/settings+/profile.two-factor.verify.tsx
 create mode 100644 app/routes/users+/$username.tsx
 create mode 100644 app/routes/users+/$username_+/notes.$noteId.tsx
 create mode 100644 app/routes/users+/$username_+/notes.$noteId_.edit.tsx
 create mode 100644 app/routes/users+/$username_+/notes.index.tsx
 create mode 100644 app/routes/users+/$username_+/notes.new.tsx
 create mode 100644 app/routes/users+/$username_+/notes.tsx
 create mode 100644 app/styles/font.css
 create mode 100644 app/styles/tailwind.css
 create mode 100644 app/utils/auth.server.ts
 create mode 100644 app/utils/cache.server.ts
 create mode 100644 app/utils/client-hints.tsx
 create mode 100644 app/utils/db.server.ts
 create mode 100644 app/utils/devtools.tsx
 create mode 100644 app/utils/email.server.ts
 create mode 100644 app/utils/env.server.ts
 create mode 100644 app/utils/flash-session.server.ts
 create mode 100644 app/utils/misc.ts
 create mode 100644 app/utils/monitoring.client.tsx
 create mode 100644 app/utils/monitoring.server.ts
 create mode 100644 app/utils/nonce-provider.ts
 create mode 100644 app/utils/permissions.server.ts
 create mode 100644 app/utils/request-info.ts
 create mode 100644 app/utils/session.server.ts
 create mode 100644 app/utils/singleton.server.ts
 create mode 100644 app/utils/timing.server.ts
 create mode 100644 app/utils/totp.server.test.ts
 create mode 100644 app/utils/totp.server.ts
 create mode 100644 app/utils/useToast.tsx
 create mode 100644 app/utils/user-validation.ts
 create mode 100644 app/utils/user.ts
 create mode 100644 app/utils/zod-extensions.ts
 create mode 100644 components.json
 create mode 100644 fly.toml
 create mode 100644 index.js
 create mode 100644 other/.dockerignore
 create mode 100644 other/Dockerfile
 create mode 100644 other/README.md
 create mode 100644 other/build-server.ts
 create mode 100644 other/litefs.yml
 create mode 100644 other/patches/@remix-run+dev+1.18.1.patch
 create mode 100644 other/sentry-create-release.js
 create mode 100644 other/setup-swap.js
 create mode 100644 other/svg-icon-template.txt
 create mode 100644 other/svg-icons/README.md
 create mode 100644 other/svg-icons/avatar.svg
 create mode 100644 other/svg-icons/camera.svg
 create mode 100644 other/svg-icons/check.svg
 create mode 100644 other/svg-icons/cross-1.svg
 create mode 100644 other/svg-icons/exit.svg
 create mode 100644 other/svg-icons/laptop.svg
 create mode 100644 other/svg-icons/lock-closed.svg
 create mode 100644 other/svg-icons/lock-open-1.svg
 create mode 100644 other/svg-icons/moon.svg
 create mode 100644 other/svg-icons/pencil-1.svg
 create mode 100644 other/svg-icons/pencil-2.svg
 create mode 100644 other/svg-icons/plus.svg
 create mode 100644 other/svg-icons/sun.svg
 create mode 100644 other/svg-icons/trash.svg
 create mode 100644 package-lock.json
 create mode 100644 package.json
 create mode 100644 playwright.config.ts
 create mode 100644 postcss.config.js
 create mode 100644 prisma/migrations/20230608211059_init/migration.sql
 create mode 100644 prisma/migrations/migration_lock.toml
 create mode 100644 prisma/schema.prisma
 create mode 100644 prisma/seed.ts
 create mode 100644 public/favicon.ico
 create mode 100644 public/favicons/README.md
 create mode 100644 public/favicons/android-chrome-192x192.png
 create mode 100644 public/favicons/android-chrome-512x512.png
 create mode 100644 public/favicons/apple-touch-icon.png
 create mode 100644 public/favicons/favicon-16x16.png
 create mode 100644 public/favicons/favicon-32x32.png
 create mode 100644 public/favicons/favicon.svg
 create mode 100644 public/favicons/mask-icon.svg
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200italic.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200italic.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-300.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-300.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-300italic.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-300italic.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-600.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-600.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-600italic.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-600italic.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-700.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-700.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-700italic.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-700italic.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-800.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-800.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-800italic.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-800italic.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-900.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-900.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-900italic.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-900italic.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-italic.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-italic.woff2
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-regular.woff
 create mode 100644 public/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-regular.woff2
 create mode 100644 public/img/user.png
 create mode 100644 public/robots.txt
 create mode 100644 public/site.webmanifest
 create mode 100644 remix.config.js
 create mode 100644 server/dev-server.js
 create mode 100644 server/index.ts
 create mode 100644 tailwind.config.ts
 create mode 100644 tests/db-utils.ts
 create mode 100644 tests/e2e/2fa.test.ts
 create mode 100644 tests/e2e/onboarding.test.ts
 create mode 100644 tests/e2e/settings-profile.test.ts
 create mode 100644 tests/fixtures/images/user/0.jpg
 create mode 100644 tests/fixtures/images/user/1.jpg
 create mode 100644 tests/fixtures/images/user/2.jpg
 create mode 100644 tests/fixtures/images/user/3.jpg
 create mode 100644 tests/fixtures/images/user/4.jpg
 create mode 100644 tests/fixtures/images/user/5.jpg
 create mode 100644 tests/fixtures/images/user/6.jpg
 create mode 100644 tests/fixtures/images/user/7.jpg
 create mode 100644 tests/fixtures/images/user/8.jpg
 create mode 100644 tests/fixtures/images/user/9.jpg
 create mode 100644 tests/fixtures/images/user/README.md
 create mode 100644 tests/fixtures/images/user/kody.png
 create mode 100644 tests/fixtures/test-profile.jpg
 create mode 100644 tests/mocks/README.md
 create mode 100644 tests/mocks/index.ts
 create mode 100644 tests/mocks/utils.ts
 create mode 100644 tests/playwright-utils.ts
 create mode 100644 tests/setup/global-setup.ts
 create mode 100644 tests/setup/matchers.cjs
 create mode 100644 tests/setup/paths.ts
 create mode 100644 tests/setup/setup-env-vars.ts
 create mode 100644 tests/setup/setup-test-env.ts
 create mode 100644 tests/setup/utils.ts
 create mode 100644 tests/setup/vitejs-plugin-react.cjs
 create mode 100644 tests/vitest-utils.ts
 create mode 100644 tests/vitest.d.ts
 create mode 100644 tsconfig.json
 create mode 100644 types/deps.d.ts
 create mode 100644 types/remix.env.d.ts
 create mode 100644 types/reset.d.ts
 create mode 100644 vitest.config.ts
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Command failed with exit code 128: git push -u origin main
    at makeError (file:///Users/da/prj/maison/remix.init/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///Users/da/prj/maison/remix.init/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async setupDeployment (file:///Users/da/prj/maison/remix.init/index.mjs:280:4)
    at async main (file:///Users/da/prj/maison/remix.init/index.mjs:88:2)
    at async module.exports (/Users/da/prj/maison/remix.init/index.js:3:2)
    at async Object.init (/Users/da/.npm/_npx/5164864a48bff686/node_modules/@remix-run/dev/dist/cli/commands.js:148:5)
    at async Object.run (/Users/da/.npm/_npx/5164864a48bff686/node_modules/@remix-run/dev/dist/cli/run.js:449:13) {
  shortMessage: 'Command failed with exit code 128: git push -u origin main',
  command: 'git push -u origin main',
  escapedCommand: 'git push -u origin main',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Looks like something went wrong setting up deployment. Sorry about that. Check the docs for instructions on how to get deployment setup yourself (https://github.com/epicweb-dev/epic-stack/blob/main/docs/deployment.md).
Setup is complete. You're now ready to rock and roll 🐨
```

**Comment by sys13** [comment]
looks like epic-stack adds
```
[remote "origin"]
	url = git@github.com:sys13/maison.git
```
while I've configured git to use https, so the git UI suggests I run `git remote add origin https://github.com/sys13/maison.git`

Maybe epic-web can fallback to the https version if the git@github one doesn't work

**Comment by kentcdodds** [comment]
Hi Daniel. This is probably related to #149. It's probably best that I remove the github step until this is resolved.
