### ISSUE TITLE
Hydration errors on fresh epic stack project

### ISSUE THREAD

**Issue by jrrmyr** [epicweb-dev/epic-stack#451]
Running a fresh project created from the epic stack template, with no changes to the generated code. Getting these errors in the console and a Flash Of Unstyled Content:

```
react-dom.development.js:86 Warning: Did not expect server HTML to contain a <tailscan-container> in <html>.
    at html
    at Document (http://localhost:3000/build/root-AF6CZHVH.js:3994:3)
    at App (http://localhost:3000/build/root-AF6CZHVH.js:4069:16)
    at SentryRoot
    at ErrorBoundary (http://localhost:3000/build/_shared/chunk-XGGBOD6K.js:14721:5)
    at errorBoundary(SentryRoot)
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-AXSBXIHO.js:3678:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-AXSBXIHO.js:4250:9)
    at DataRoutes (http://localhost:3000/build/_shared/chunk-AXSBXIHO.js:3964:5)
    at Router (http://localhost:3000/build/_shared/chunk-AXSBXIHO.js:4043:15)
    at RouterProvider (http://localhost:3000/build/_shared/chunk-AXSBXIHO.js:3913:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-AXSBXIHO.js:6542:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-AXSBXIHO.js:7127:40)
overrideMethod @ console.js:213
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
warnForDeletedHydratableElement @ react-dom.development.js:10477
didNotHydrateInstance @ react-dom.development.js:11424
warnUnhydratedInstance @ react-dom.development.js:12313
warnIfUnhydratedTailNodes @ react-dom.development.js:12707
popHydrationState @ react-dom.development.js:12677
completeWork @ react-dom.development.js:22176
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 1 more frame
Show less
react-dom.development.js:86 Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.
overrideMethod @ console.js:213
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
errorHydratingContainer @ react-dom.development.js:11473
recoverFromConcurrentError @ react-dom.development.js:25846
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 1 more frame
Show less
react-dom.development.js:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at popHydrationState (react-dom.development.js:12678:9)
    at completeWork (react-dom.development.js:22176:30)
    at completeUnitOfWork (react-dom.development.js:26596:16)
    at performUnitOfWork (react-dom.development.js:26568:5)
    at workLoopConcurrent (react-dom.development.js:26543:5)
    at renderRootConcurrent (react-dom.development.js:26505:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:38)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
throwOnHydrationMismatch @ react-dom.development.js:12507
popHydrationState @ react-dom.development.js:12678
completeWork @ react-dom.development.js:22176
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:19849 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js:19849:57)
    at beginWork (react-dom.development.js:21615:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
```

**Comment by luksch42** [comment]
Do you have an browser extension installed?

**Comment by sys13** [comment]
probably this one: https://chrome.google.com/webstore/detail/tailscan/ehlgpljoffpijelfiegjpkfanlfhgeae

**Comment by luksch42** [comment]
Just try to deactivate it and check if the hydration error persists

**Comment by jrrmyr** [comment]
> probably this one: https://chrome.google.com/webstore/detail/tailscan/ehlgpljoffpijelfiegjpkfanlfhgeae

Duh.. 🤦 Yes, this extension was causing the errors. Thank you.
