### ISSUE TITLE
Issue with install

### ISSUE THREAD

**Issue by willwillis** [epicweb-dev/epic-stack#501]
```
$ npx create-epic-app@latest
Need to install the following packages:
create-epic-app@1.0.4
Ok to proceed? (y) 

 remix   v2.1.0 💿 Let's build a better website...

   dir   Where should we create your new project?
         ./my-epic-site

      ◼  Template: Using epicweb-dev/epic-stack...
      ✔  Template copied

      ✔  Dependencies installed


      ▲  Oh no! Failed to initialize git.
node:internal/errors:866
  const err = new Error(message);
              ^

Error: Command failed: npx create-remix@latest --yes --install --init-script --template epicweb-dev/epic-stack
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at createEpicApp (file:///home/will/.npm/_npx/cac6a35e04d35842/node_modules/create-epic-app/index.js:7:3)
    at file:///home/will/.npm/_npx/cac6a35e04d35842/node_modules/create-epic-app/index.js:10:1
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19800,
  stdout: null,
  stderr: null
}

Node.js v20.8.0
```

```

 pacman -Ss node | grep -i installed
extra/node-gyp 9.4.0-1 [installed]
extra/nodejs 20.8.0-1 [installed]
extra/nodejs-nopt 7.2.0-1 [installed]
```

The folder and files get created, but the script hangs when I attempt to run

```
npm run dev

> predev
> npm run build:icons --silent

Generated 27 icons

> dev
> remix dev -c "node ./server/dev-server.js" --manual


 💿  remix dev

 info  building...
 info  built (1.9s)
10:17:31 PM [tsx] rerunning
Debugger listening on ws://127.0.0.1:9229/f6295eb5-064d-4e83-b0f9-fee8ea9e3582
For help, see: https://nodejs.org/en/docs/inspector
TypeError: Cannot read properties of undefined (reading 'startsWith')
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at file:///home/will/x/code/my-epic-site/tests/mocks/github.ts:1:2646
```

**Comment by ivorpad** [comment]
@willwillis https://github.com/epicweb-dev/epic-stack/issues/496

**Comment by kentcdodds** [comment]
Closing in favor of #496
