### ISSUE TITLE
npx Getting Started command fails with error

### ISSUE THREAD

**Issue by aydrian** [epicweb-dev/epic-stack#640]
Following the [Getting Started](https://github.com/epicweb-dev/epic-stack/blob/main/docs/getting-started.md) documentation. When I run the `npx` command: `npx create-epic-app@latest` using either Node version 18 or 20, it fails with the following error:
```
node:internal/errors:932
  const err = new Error(message);
              ^

Error: Command failed: npx --yes create-remix@latest --install --no-git-init --init-script --template epicweb-dev/epic-stack
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at createEpicApp (file:///Users/aydrian/.npm/_npx/cac6a35e04d35842/node_modules/create-epic-app/index.js:7:3)
    at file:///Users/aydrian/.npm/_npx/cac6a35e04d35842/node_modules/create-epic-app/index.js:10:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13322,
  stdout: null,
  stderr: null
}
```

**Comment by kentcdodds** [comment]
Unfortunately that error doesn't provide any actionable information. Are there no other errors? I just tried myself and it worked as expected.

**Comment by aydrian** [comment]
Okay. This was my bad. I forgot the `.` when I provided the folder, so it received `/custom-folder` instead of `./custom-folder`. Looks like it just wasn't gracefully failing when it hit possibly a permission error.

**Comment by kentcdodds** [comment]
Glad you worked it out!
