### ISSUE TITLE
Phosphor icons Unexpected token error

### ISSUE THREAD

**Issue by PabloCorso** [epicweb-dev/epic-stack#831]
I'm having an issue when trying to add the phosphor-icons package using the @sly-cli/sly tool. Not sure if I'm using it right.

Using:
```sh
npx @sly-cli/sly add phosphor-icons sparkle
```

Output:
```
SyntaxError: Unexpected token 'U', "Unexpected"... is not valid JSON
Error: Failed to fetch registry from https://sly-cli.fly.dev.
file:///path/to/project/node_modules/@sly-cli/sly/dist/index.js:288
    throw new Error(`Failed to fetch tree from registry.`);
          ^

Error: Failed to fetch tree from registry.
    at file:///path/to/project/node_modules/@sly-cli/sly/dist/index.js:288:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchTree (file:///path/to/project/node_modules/@sly-cli/sly/dist/index.js:280:18)
    at async Command.<anonymous> (file:///path/to/project/node_modules/@sly-cli/sly/dist/index.js:618:19)
```

Additional Context:

I noticed that there have been recent updates to the phosphor-icons library. According to their [GitHub page](https://github.com/phosphor-icons/web), they are replacing the existing `phosphor-icons` package with `@phosphor-icons/web`.

**Comment by PabloCorso** [comment]
Ops wrong project. Closing issue.
