### ISSUE TITLE
`npm run dev` -> `TypeError: routeSegments.at is not a function`

### ISSUE THREAD

**Issue by timothymalcham** [epicweb-dev/epic-stack#86]
Wanted to try out the stack, installed via the [getting-started.md](https://github.com/epicweb-dev/epic-stack/blob/main/docs/getting-started.md) instructions. Ran the setup command, and then tried to boot up the server (without touching any files or code) and got this:

```
➜ npm run dev

> dev
> remix dev -c "npm run dev:server" --no-restart

TypeError: routeSegments.at is not a function
    at getRouteSegments (/Users/timothymalcham/dev/uu/node_modules/remix-flat-routes/dist/index.js:356:23)
    at getRouteInfo (/Users/timothymalcham/dev/uu/node_modules/remix-flat-routes/dist/index.js:210:25)
    at /Users/timothymalcham/dev/uu/node_modules/remix-flat-routes/dist/index.js:119:33
    at defaultVisitFiles (/Users/timothymalcham/dev/uu/node_modules/remix-flat-routes/dist/index.js:382:13)
    at defaultVisitFiles (/Users/timothymalcham/dev/uu/node_modules/remix-flat-routes/dist/index.js:379:13)
    at _flatRoutes (/Users/timothymalcham/dev/uu/node_modules/remix-flat-routes/dist/index.js:113:9)
    at flatRoutes (/Users/timothymalcham/dev/uu/node_modules/remix-flat-routes/dist/index.js:44:20)
    at Object.routes (file:///Users/timothymalcham/dev/uu/remix.config.js:22:10)
    at Object.readConfig (/Users/timothymalcham/dev/uu/node_modules/@remix-run/dev/dist/config.js:248:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Is there a recommended way of resolving this?

**Comment by rajeshg** [comment]
Tried reproducing this with the latest version and haven't run into this myself.
OS: Windows 10
Environment: WSL2

Based on the error log, obviously it's thrown from the remix-flat-routes package. Possibly a rare edge case, that I am having a hard time reproducing.

@timothymalcham still experiencing this?

**Comment by CarlaTeo** [comment]
I had the same problem, it was the node version. 
Found the solution in the remix-flat-routes git: https://github.com/kiliman/remix-flat-routes/issues/44
