### ISSUE TITLE
Running npx create-epic-app@latest fails on build step

### ISSUE THREAD

**Issue by 2wce** [epicweb-dev/epic-stack#861]
When i try to create a new project it fails on the build step. here's a snippet of the output below

```
 remix   v2.12.1 💿 Let's build a better website...

   dir   Where should we create your new project?
         ./my-remix-app

      ◼  Template: Using epicweb-dev/epic-stack...
      ✔  Template copied
      ◼  Nice! Git has already been initialized

      ✔  Dependencies installed
      ✔  Dependencies for remix.init script installed

      ◼  Running template's remix.init script...


> setup
> npm run build && prisma generate && prisma migrate deploy && prisma db seed && playwright install


> build
> run-s build:*


> build:icons
> tsx ./other/build-icons.ts

Generated 27 icons

> build:remix
> remix vite:build

vite v5.3.4 building for production...

  ⚠️  Source maps are enabled in production
     This makes your server code publicly
     visible in the browser. This is highly
     discouraged! If you insist, ensure that
     you are using environment variables for
     secrets and not hard-coding them in
     your source code.

✓ 131 modules transformed.
x Build failed in 366ms
[vite]: Rollup failed to resolve import "@/components/date-range-picker" from "/Users/me/my-remix-app/app/routes/_index.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/me/my-remix-app/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:65883:17)
    at onwarn (/Users/me/my-remix-app/node_modules/@remix-run/dev/dist/vite/plugin.js:618:13)
    at onRollupWarning (file:///Users/me/my-remix-app/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:65916:5)
    at onwarn (file:///Users/me/my-remix-app/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:65578:7)
    at file:///Users/me/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:18514:13
    at Object.logger [as onLog] (file:///Users/me/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:20162:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/me/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:19104:26)
    at file:///Users/me/my-remix-app/node_modules/rollup/dist/es/shared/node-entry.js:19062:26 {
  watchFiles: [
   .. lists all watched files here
  ]
}
ERROR: "build:remix" exited with 1.

      ▲  Oh no! Template's remix.init script failed
node:internal/errors:932
  const err = new Error(message);
              ^

Error: Command failed: npx --yes create-remix@latest --install --no-git-init --init-script --template epicweb-dev/epic-stack
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at createEpicApp (file:///Users/me/.npm/_npx/cac6a35e04d35842/node_modules/create-epic-app/index.js:7:3)
    at file:///Users/me/.npm/_npx/cac6a35e04d35842/node_modules/create-epic-app/index.js:10:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 96779,
  stdout: null,
  stderr: null
}

```
 I am using this Node version: v20.10.0

**Comment by 2wce** [comment]
sorry this only happened because there was another folder with the same name & the cli started adding files to a different project

**Comment by kentcdodds** [comment]
Glad you worked it out!
